stages:
  - test

deploy:webplayer.test.hls.tv:
  stage: test
  tags:
    - webplayer.test.hls.tv
  only:
    - master
  script:
    - bash
    - cd /var/www/webplayer.hls.tv
    - git add .
    - git checkout -f master
    - git pull origin master
    - npm i
    - unset CI
    - npm run build
    - rm -rf public
    - mv build public
  after_script:
    - echo "Successfully deployed webplayer.test.hls.tv"
  environment:
       webplayer.test.hls.tv